#!/bin/bash -ex

#define variables
share=/srv/ampache
ampache_src=https://github.com/ampache/ampache/archive/master.tar.gz
MYSQL_PASS=turnkey
DB_NAME=ampache
DB_USER=ampache
DB_PASS=ampache

#Start Daemons
/etc/init.d/mysql start
/etc/init.d/apache2 start

#create dir for samba share
mkdir $share

#Set permissions for samba share
chmod 777 $share

#Change MySQL Root Account
mysqladmin -u root password $MYSQL_PASS

# setup the database
MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"
MYSQL_ADMIN="mysqladmin --user=root --password=$MYSQL_PASS"

$MYSQL_ADMIN create $DB_NAME
$MYSQL_BATCH --execute "grant all privileges on $DB_NAME.* to $DB_USER@localhost identified by '$DB_PASS'; flush privileges;"

#Deal with Ampache
wget $ampache_src -O /tmp/ampache.tar.gz
tar xvzf /tmp/ampache.tar.gz -C /var/www/
chown -R www-data:www-data /var/www/ampache-master
mv /var/www/ampache-master /var/www/ampache

#Ampache site
a2dissite default
a2ensite ampache
/etc/init.d/apache2 reload

#Ampache DB Install
php /var/www/ampache/bin/install/install_db.inc -U root -P $MYSQL_PASS -h localhost -d $DB_NAME -w / -u $DB_USER -p $DB_PASS -f
mysql --user=root --password=$MYSQL_PASS -D ampache -e "UPDATE preference SET value = 'Fresh' where id = 33;"
#Symbolic Link for ampache.cfg.php
#mkdir /etc/ampache
#ln -s /etc/ampache/ampache.cfg.php /usr/share/ampache/www/config/ampache.cfg.php

# Configure samba share
echo "[media]" >> /etc/samba/smb.conf
echo "     writeable = yes" >> /etc/samba/smb.conf
echo "     public = yes" >> /etc/samba/smb.conf
echo "     path = $share" >> /etc/samba/smb.conf
#Stop MySQL Server
/etc/init.d/mysql stop
#Stop Apache Server
/etc/init.d/apache2 stop
